---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  organizationId: "06ae1d0a-2e36-4299-958d-b4930153f890"
  secretName: tailscale-auth
  authToken:
    secretName: bw-auth-token
    secretKey: token
  onlyMappedSecrets: true
  map:
    - bwSecretId: "7450b5cd-9d7a-45c6-a57e-b496006b323f"
      secretKeyName: TS_AUTHKEY
