---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  organizationId: "06ae1d0a-2e36-4299-958d-b4930153f890"
  secretName: tailscale-auth
  authToken:
    secretName: bw-auth-token
    secretKey: token
  onlyMappedSecrets: true
  map:
    - bwSecretId: "10c3a577-1217-4817-bb76-b496006db49c"
      secretKeyName: TS_AUTHKEY
