---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflared
spec:
  organizationId: "06ae1d0a-2e36-4299-958d-b4930153f890"
  secretName: cloudflare-tunnel-token
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: "fd5cb98a-8112-48ce-bf6a-b49b002be284"
      secretKeyName: token
