---
# Common role defaults

# Packages for all nodes (cross-platform)
common_packages:
  - curl
  - jq
  - tar
  - vim

# OS-specific packages (installed before common_packages)
common_packages_debian:
  - glances
  - nfs-common
common_packages_redhat:
  - epel-release
