---
# Grafana admin credentials from Bitwarden Secrets Manager
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  organizationId: "06ae1d0a-2e36-4299-958d-b4930153f890"
  secretName: grafana-admin
  authToken:
    secretName: bw-auth-token
    secretKey: token
  onlyMappedSecrets: true
  map:
    - bwSecretId: "b5f19c39-8b20-4aac-b1a1-b49b008834da"
      secretKeyName: admin-password
