---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
  namespace: media
  labels:
    app: media-manager
    component: kavita
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: media-manager
      component: kavita
  template:
    metadata:
      labels:
        app: media-manager
        component: kavita
    spec:
      hostname: kavita
      containers:
      - image: jvmilazz0/kavita:0.9.0.2
        name: kavita
        ports:
        - containerPort: 5000
          name: webui
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 768Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: config
          mountPath: /kavita/config
        - name: comics
          mountPath: /data/comics
        - name: books
          mountPath: /data/books
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: kavita-pvc
      - name: comics
        hostPath:
          path: /mnt/data/library/comics
          type: Directory
      - name: books
        hostPath:
          path: /mnt/data/library/books
          type: Directory
      restartPolicy: Always
      nodeName: xialing
